server
  port: 8090

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8092/eureka
      
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: health,gateway

zipkin:
  baseUrl: "zipkin:9411"
